// Thin wrapper over `RTCPeerConnection` that adapts the browser API to
// the project's "signaling via Blocks Data" world:
//
//   - Local ICE candidates generated by the browser are accumulated
//     in `pendingLocalCandidates` so the polling loop can drain them
//     and POST them to the cloud row in one mutation pass.
//
//   - Remote ICE candidates are deduped by `candidate` string via the
//     `appliedRemoteCandidates` Set — the 2s poll will re-read the
//     same merged blob every tick, and double-adding an ICE candidate
//     throws on some browsers.
//
//   - `onTrack` hands the remote MediaStream to the caller so the
//     `<video>` element can bind via `srcObject`. Same for
//     `onConnectionStateChange` so the caller can react to ICE
//     failures (state === 'failed') by tearing down and toasting.
//
// This module is intentionally pure (no React, no hooks) so the same
// logic is trivially unit-testable and reusable from any entry point
// (the caller's CallDialog, the recipient's CallDialog, future call
// components).

import type { CallSignalIceCandidate } from "./data";

// Public STUN server — sufficient for the v1 path. Calls behind
// strict NAT / corporate firewalls may fail to establish because
// there's no TURN server. Documented in CallDialog.tsx + the Phone /
// Video button tooltips + the ICE-failure toast.
const DEFAULT_STUN_SERVERS: RTCIceServer[] = [
  { urls: "stun:stun.l.google.com:19302" },
];

export interface IceExchangeCallbacks {
  onIceCandidate: (c: CallSignalIceCandidate) => void;
  onTrack: (stream: MediaStream) => void;
  /** Fires for both `iceConnectionState` and `connectionState`
   *  transitions. ICE states include `'completed'` which the
   *  peer-connection state union doesn't, so the type is widened to
   *  the ICE union — callers that only care about `'failed'` should
   *  match that single value. */
  onConnectionStateChange: (state: RTCIceConnectionState | RTCPeerConnectionState) => void;
}

export interface IceExchangeController {
  pc: RTCPeerConnection;
  /** Track which remote candidates have already been added — keyed by
   * `candidate` string. The 2s poll loop walks `data.iceCandidates`
   * and skips any candidate in this set, so duplicate adds from a
   * re-read don't throw on browsers that reject them. */
  appliedRemoteCandidates: Set<string>;
  /** Local candidates generated since the last `drainPendingLocal…`
   * call. The polling loop drains and POSTs them as a batch so a
   * single mutation can carry the latest trickle. */
  pendingLocalCandidates: CallSignalIceCandidate[];
  /** Add one remote candidate if it hasn't been applied yet. */
  applyRemoteCandidate: (c: CallSignalIceCandidate) => Promise<void>;
  /** Returns and clears the pending local candidate queue — the
   * caller POSTs the returned array to the signaling row. */
  drainPendingLocalCandidates: () => CallSignalIceCandidate[];
  /** Close the PC + remove every track from the local stream. Idempotent. */
  teardown: (localStream: MediaStream | null) => void;
}

export function createIceExchange(
  localStream: MediaStream,
  callbacks: IceExchangeCallbacks,
  iceServers: RTCIceServer[] = DEFAULT_STUN_SERVERS,
): IceExchangeController {
  // Use the canonical adapter: `{iceServers}`. Fall back to the
  // browser default when none are configured (which is the same as
  // public STUN anyway, but explicit is better than implicit).
  const pc = new RTCPeerConnection({ iceServers });

  const controller: IceExchangeController = {
    pc,
    appliedRemoteCandidates: new Set<string>(),
    pendingLocalCandidates: [],
    applyRemoteCandidate: async (c) => {
      if (controller.appliedRemoteCandidates.has(c.candidate)) return;
      try {
        await pc.addIceCandidate({
          candidate: c.candidate,
          sdpMid: c.sdpMid,
          sdpMLineIndex: c.sdpMLineIndex,
        });
        controller.appliedRemoteCandidates.add(c.candidate);
      } catch (err) {
        // Stale candidate (e.g. from an ended call's row that's
        // still being polled) — log + skip rather than crash the
        // in-call UI.
        console.warn("[callSignals] failed to addIceCandidate", err);
      }
    },
    drainPendingLocalCandidates: () => {
      const drained = controller.pendingLocalCandidates;
      controller.pendingLocalCandidates = [];
      return drained;
    },
    teardown: (localStream: MediaStream | null) => {
      try {
        // Closing the PC fires `iceconnectionstatechange === 'closed'`
        // on some browsers, which the IncomingCallDialog already
        // handles; we don't need to chase it from here.
        pc.getSenders().forEach((sender) => {
          try {
            pc.removeTrack(sender);
          } catch {
            // removeTrack can throw if the sender was already removed
            // by the RTCPeerConnection teardown sequence — silent.
          }
        });
        pc.close();
      } catch (err) {
        console.warn("[callSignals] pc.close failed", err);
      }
      if (localStream) {
        localStream.getTracks().forEach((t) => {
          try {
            t.stop();
          } catch {
            // Stop can throw on Firefox if the track is already ended.
          }
        });
      }
    },
  };

  // Push every track from the local stream into the PC. Audio only
  // gets one track; video at most one (the user-facing camera).
  for (const track of localStream.getTracks()) {
    pc.addTrack(track, localStream);
  }

  pc.onicecandidate = (event) => {
    if (event.candidate) {
      controller.pendingLocalCandidates.push({
        candidate: event.candidate.candidate,
        sdpMid: event.candidate.sdpMid ?? null,
        sdpMLineIndex: event.candidate.sdpMLineIndex ?? null,
      });
      // Best-effort: notify the caller so a UI chip can show
      // "Gathering ICE candidates…". The polling loop also drains the
      // queue, so the callback is a hint, not the source of truth.
      callbacks.onIceCandidate({
        candidate: event.candidate.candidate,
        sdpMid: event.candidate.sdpMid ?? null,
        sdpMLineIndex: event.candidate.sdpMLineIndex ?? null,
      });
    }
  };

  pc.ontrack = (event) => {
    // `event.streams[0]` is the aggregate stream when the sender
    // attached multiple tracks. Fall back to constructing a fresh
    // MediaStream from the single track on browsers that don't
    // populate `streams` (rare but happens on some Safari builds).
    const remoteStream = event.streams[0] ?? new MediaStream([event.track]);
    callbacks.onTrack(remoteStream);
  };

  pc.oniceconnectionstatechange = () => {
    callbacks.onConnectionStateChange(pc.iceConnectionState);
  };

  pc.onconnectionstatechange = () => {
    callbacks.onConnectionStateChange(pc.connectionState);
  };

  return controller;
}
