// Interactive shell bridge — spawns a real PTY (PowerShell on Windows,
// bash on POSIX) for the WorkspacePage's terminal panel and shuttles
// bytes between the browser's WebSocket and the pseudo-terminal.
//
// Why PTY instead of plain `child_process.spawn`
// ──────────────────────────────────────────────
// `npm install`, `npx create-…`, `pnpm`, and most build tools
// detect whether stdin is a TTY and degrade (no progress bar, no
// color, prompt disabled) when it isn't. node-pty exposes the
// ConPTY/winpty handle so the shell — and everything it runs —
// behaves as if attached to a real terminal. Without this the
// terminal panel would be a glorified `execSync` and `npm i` would
// sit silently for a minute.
//
// Protocol (newline-delimited JSON over the WS)
// ────────────────────────────────────────────
// Browser → server:
//   { type: "input",  data: "<base64>" }     // user keystrokes (data is
//                                            // bytes from xterm's onData
//                                            // — usually ASCII/UTF-8
//                                            // but encoded losslessly
//                                            // via base64)
//   { type: "resize", cols: number, rows: number }
//   { type: "ping",   ts: number }          // OPTIONAL keepalive; the
//                                            // WS protocol's own
//                                            // PING/PONG is enough
//                                            // for most proxies.
//
// Server → browser:
//   { type: "started", shell: "powershell.exe", cwd: "..." }
//   { type: "output", data: "<base64>" }     // PTY output bytes
//                                            // (ANSI escapes
//                                            // included)
//   { type: "exit",   code: number|null, signal?: string }
//   { type: "pong",   ts: number }
//
// Lifecycle
// ─────────────────────────────────────────────────────────────────────
//   1. Browser opens `ws://…/dev-terminal/shell?workspaceId=…&cwd=…`.
//   2. mcp-server verifies the workspaceId and `cwd` (must resolve
//      under the user-picked folder) and spawns the PTY there.
//   3. Bytes flow in both directions until the PTY exits or the
//      WS closes; either side tears down the other.
//   4. SIGTERM the PTY on WS close (graceful) so child processes
//      don't leak.
//
// Why we don't go through agentBridge.ts (yet)
// ─────────────────────────────────────────────
// Today this runs locally only (mcp-server runs on the user's machine
// in dev mode). When AGENT_BRIDGE_ENABLED=1 in production, the
// forwarder could ferry `input`/`output` frames through the agent
// just like HTTP requests — the wire format above is already shaped
// for that. Until that's a requirement, keeping it simple: WS ↔ PTY
// in this process.

import * as os from "node:os";
import * as path from "node:path";
import { existsSync, statSync } from "node:fs";
import { resolve } from "node:path";
import type { WebSocket } from "ws";

// node-pty is loaded lazily so a freshly-booted mcp-server in CI
// (where ConPTY binaries may be missing) doesn't throw at import
// time. The WS route catches the missing-export case and 503s with
// a useful message.
type Pty = {
  pid: number;
  onData: (cb: (data: string) => void) => void;
  onExit: (cb: (e: { exitCode: number; signal?: number }) => void) => void;
  write: (data: string) => void;
  resize: (cols: number, rows: number) => void;
  kill: (signal?: string) => void;
};
let ptyModule: typeof import("node-pty") | null = null;
async function loadPty(): Promise<typeof import("node-pty")> {
  if (ptyModule) return ptyModule;
  try {
    ptyModule = await import("node-pty");
    return ptyModule;
  } catch (err) {
    throw new Error(
      `node-pty failed to load: ${(err as Error).message}. On Windows this usually means the C++ build tools (MSVC + Windows SDK) are missing — install them or copy a prebuilt binary into node_modules/node-pty/build/Release/.`,
    );
  }
}

export interface ShellOptions {
  /** Absolute path to spawn the shell in. Validated by the route
   *  layer — must resolve to an existing directory. */
  cwd: string;
  /** Workspace identity — used to key the persistent-shell map so two
   *  workspaces can have their own PTY even if they pick the same
   *  folder. Required; route refuses the WS without it. */
  workspaceId: string;
  /** Per-tab stable id — distinguishes multiple terminals open in
   *  the same workspace+folder. Generated by the panel on `[+]` and
   *  persisted in localStorage so refresh keeps the tab identity.
   *  Required; route refuses the WS without it. */
  terminalId: string;
  /** Pick a specific shell by its `ShellDescriptor.id`. When set,
   *  bypasses `defaultShell()` — the user picked it from the panel
   *  dropdown. Unknown id → falls back to default. */
  shellId?: string;
  /** Environment overrides. Merged onto `process.env`. */
  env?: Record<string, string>;
  /** Initial terminal size. Defaults to 80×24 (matches xterm.js'
   *  initial measurement before the first fit). */
  cols?: number;
  rows?: number;
}

export interface ShellInfo {
  shell: string;
  args: string[];
  pid: number;
  /** True when the WS attached to a pre-existing PTY (refresh /
     /// re-navigation). False on a fresh spawn. */
  resumed: boolean;
}

// ─────────────────────────────────────────────────────────────────────
//  Persistent shell registry
// ─────────────────────────────────────────────────────────────────────
//
// One PTY per `(workspaceId, cwd, terminalId)`. The PTY outlives any
// individual WebSocket — when the browser refreshes / navigates away
// / closes the tab, the PTY keeps running so `npm run dev` (and any
// other long-running command) keeps going. The user kills the shell
// by pressing Ctrl+C inside the terminal itself, which is a *natural*
// shell exit — `handle.onExit` fires and tears the record down.
//
// `ShellOptions.workspaceId` + `ShellOptions.terminalId` become part
// of the composite key so two workspaces can't collide even if they
// pick the same folder, and a single workspace can keep multiple
// terminals open (each tab is its own PTY).

const SHELL_KEY_SEP = "\0"; // not valid in cwd / workspaceId / terminalId strings

function persistentShellKey(
  workspaceId: string,
  cwd: string,
  terminalId: string,
): string {
  return `${workspaceId}${SHELL_KEY_SEP}${cwd}${SHELL_KEY_SEP}${terminalId}`;
}

interface PersistentShell {
  id: string;
  workspaceId: string;
  cwd: string;
  shell: string;
  shellPath: string;
  args: string[];
  pty: Pty;
  pid: number;
  startedAt: number;
  /** Bumped from `handle.onData` — hook for a future idle-GC. */
  lastOutputAt: number;
  /** All currently-attached browser sockets. Each receives every
   *  `output` frame from the PTY. A socket dropping only removes
   *  itself from this set — the PTY stays alive. */
  listeners: Set<WebSocket>;
  /** Set when the PTY actually exited. The record is kept briefly
   *  (60s GC below) so a browser that's mid-reconnect sees the
   *  `exit` frame instead of a fresh shell. */
  exited: boolean;
  exitCode: number | null;
  exitSignal: number | null;
  /** Set by `stopPersistentShell` so a racing WS attach knows to
   *  spawn fresh rather than reattaching to a PTY that's about to
   *  die. */
  stopRequested: boolean;
}

/** 60s — long enough that an in-flight browser reconnect lands and
 *  sees the `exit` frame, short enough that a forgotten shell
 *  doesn't leak indefinitely. */
const PERSISTENT_SHELL_GC_MS = 60_000;

const persistentShells = new Map<string, PersistentShell>();

export function persistentShellId(
  workspaceId: string,
  cwd: string,
  terminalId: string,
): string {
  return persistentShellKey(workspaceId, cwd, terminalId);
}

export function getPersistentShell(id: string): PersistentShell | undefined {
  return persistentShells.get(id);
}

export function listPersistentShells(workspaceId?: string): PersistentShell[] {
  const all = [...persistentShells.values()];
  if (!workspaceId) return all;
  return all.filter((r) => r.workspaceId === workspaceId);
}

// Pick the platform-appropriate shell.
//
// We don't honour `$SHELL` on POSIX — that variable lets the user
// accidentally land on `/bin/zsh` (no theme, no prompt init),
// which is a poor first impression. /bin/bash is universally
// present on the dev machines we've shipped.
//
// On Windows we prefer PowerShell 7 (`pwsh.exe`) over the legacy
// Windows PowerShell 5.1 (`powershell.exe`). PS7 is the actively
// maintained one and doesn't suffer from the "Loading managed
// Windows PowerShell failed with error 8009001D" issue some
// machines hit with v5.1 (typically a CLR/DLL mismatch). When
// neither PowerShell is installed we fall back to cmd.exe — still
// a real PTY, npm works fine, prompt is the standard `C:\…>`.
//
// Detection happens lazily so a fresh import of this module
// doesn't shell out synchronously.
let cachedShell: { shell: string; args: string[] } | null = null;
function defaultShell(): { shell: string; args: string[] } {
  if (cachedShell) return cachedShell;
  if (os.platform() === "win32") {
    // Order: pwsh.exe (PS7) → powershell.exe (legacy PS) → cmd.exe.
    // whichSync is on PATH in stock Windows 10/11.
    if (whichSync("pwsh.exe")) {
      // PowerShell 7. -NoLogo keeps the banner out of the way;
      // interactive use is the default so `-NoExit` would be a
      // no-op (kept implicit).
      cachedShell = { shell: "pwsh.exe", args: ["-NoLogo"] };
    } else if (whichSync("powershell.exe")) {
      cachedShell = { shell: "powershell.exe", args: ["-NoLogo"] };
    } else {
      // Last-resort fallback. cmd.exe is on every Windows install;
      // /q keeps the banner out of the panel.
      cachedShell = { shell: "cmd.exe", args: ["/q"] };
    }
  } else {
    cachedShell = { shell: "/bin/bash", args: ["-l"] };
  }
  return cachedShell;
}

// Shell catalog — the dropdown menu the panel renders. Each entry
// carries an `id` (the stable, language-neutral key sent over the
// WS `shellId` query param) and a `command` + `args` pair that
// node-pty can spawn directly. `label` is the user-facing string
// (rendered verbatim — let i18n happen on the client if ever
// needed). `available` is computed at request time via `whichSync`.
//
// We deliberately don't auto-detect on the client side: detection
// needs to read `process.env.PATH` server-side, which the browser
// can't see. The list ships in `started`-frame-equivalent
// `GET /dev-terminal/shells` so the dropdown is honest about
// what's actually launchable on this machine.
export interface ShellDescriptor {
  id: string;
  /** Stable id sent over the WS `shellId` query param. Same as
   *  `id`; exposed separately so the route can decode it without
   *  type-cast acrobatics. */
  shellId: string;
  label: string;
  /** True when `whichSync(label)` finds the binary. False = the
   *  dropdown disables this entry but keeps it visible so the
   *  user knows "Git Bash isn't installed, click for setup help". */
  available: boolean;
  /** Absolute path on disk — exposed so the UI can show "Git Bash
   *  → C:\Program Files\Git\bin\bash.exe" in the disabled-tooltip. */
  resolvedPath: string | null;
}

const SHELL_CATALOG: ReadonlyArray<{
  id: string;
  /** Binary name to look up via whichSync. May differ from id (e.g.
   *  "git-bash" → "bash.exe"). */
  binary: string;
  /** Args to pass at spawn time. */
  args: string[];
  /** Display label. */
  label: string;
}> = os.platform() === "win32"
  ? [
      { id: "pwsh", binary: "pwsh.exe", args: ["-NoLogo"], label: "PowerShell 7" },
      { id: "powershell", binary: "powershell.exe", args: ["-NoLogo"], label: "Windows PowerShell" },
      { id: "cmd", binary: "cmd.exe", args: ["/q"], label: "Command Prompt" },
      // Git for Windows installs bash.exe under
      //   C:\Program Files\Git\bin\bash.exe
      // and (more usefully for VS Code parity) registers `bash.exe`
      // on PATH automatically. A separate `bash` entry keeps the
      // dropdown honest about which bash — Git's mintty-aware build
      // — is going to spawn.
      { id: "git-bash", binary: "bash.exe", args: ["-l"], label: "Git Bash" },
      { id: "wsl", binary: "wsl.exe", args: [], label: "WSL (default distro)" },
    ]
  : [
      { id: "bash", binary: "bash", args: ["-l"], label: "Bash" },
      { id: "zsh", binary: "zsh", args: ["-l"], label: "Zsh" },
      { id: "sh", binary: "sh", args: ["-l"], label: "POSIX sh" },
    ];

/** Public list for `GET /dev-terminal/shells`. The route is plain
 *  JSON — no caching headers because the binary discovery cost
 *  is negligible (`existsSync` × ~6 paths). */
export function listShells(): ShellDescriptor[] {
  return SHELL_CATALOG.map((s) => {
    const resolved = whichSync(s.binary);
    return {
      id: s.id,
      shellId: s.id,
      label: s.label,
      available: resolved !== null,
      resolvedPath: resolved,
    };
  });
}

/** Resolve a `shellId` (from the WS query string) to the spawn
 *  tuple. Unknown id → falls back to `defaultShell()` so a typo
 *  or older client doesn't 400 — the user still gets a working
 *  shell. */
function resolveShellById(shellId: string | undefined): { shell: string; args: string[] } {
  if (shellId) {
    const entry = SHELL_CATALOG.find((s) => s.id === shellId);
    if (entry) {
      const resolved = whichSync(entry.binary);
      if (resolved) {
        return { shell: resolved, args: entry.args };
      }
      // Fall through — the binary isn't installed. The PTY spawn will
      // fail with ENOENT and the client gets the error via the
      // standard `onError` channel.
    }
  }
  return defaultShell();
}

// Tiny `which` — node 20 doesn't ship one in the standard library
// and pulling in a 200-line `which` package for a one-off shell
// detection feels excessive.
function whichSync(cmd: string): string | null {
  const dirs = (process.env.PATH ?? "").split(path.delimiter).filter(Boolean);
  const win = os.platform() === "win32";
  const exts = win
    ? (process.env.PATHEXT ?? ".EXE;.BAT;.CMD").split(";").filter(Boolean)
    : [];
  // For each directory, try the literal command first — Windows
  // `where.exe` semantics honour the name as-given. Then (only if
  // the command has no extension) iterate PATHEXT to grow suffixes
  // like `wsl` → `wsl.EXE`. Appending `.EXE` to an already-extended
  // name like `cmd.exe` would build `cmd.exe.EXE`, which is never
  // a real file.
  const hasExt = win && exts.some((e) => cmd.toLowerCase().endsWith(e.toLowerCase()));
  for (const dir of dirs) {
    const tries: string[] = [cmd];
    if (win && !hasExt) {
      for (const e of exts) tries.push(cmd + e);
    }
    for (const name of tries) {
      const candidate = path.join(dir, name);
      try {
        if (existsSync(candidate)) {
          const st = statSync(candidate);
          if (st.isFile() || st.isSymbolicLink()) return candidate;
        }
      } catch {
        /* permission errors etc. — try next */
      }
    }
  }
  return null;
}

// -- The actual attachment ──────────────────────────────────────────────
//
// Look up an existing PTY in `persistentShells` (key = workspaceId +
// cwd). If a live one exists, attach the new WS as an additional
// listener. Otherwise spawn fresh and store the record.
//
// The PTY dies only when:
//   1. The shell process itself exits (Ctrl+C, `exit`, crash, etc.)
//      — fires `handle.onExit` and tears the record down.
//   2. `stopPersistentShell` is called (no UI calls this today; the
//      user types Ctrl+C inside the terminal).
//   3. `shutdownAllPersistentShells` is called (SIGINT/SIGTERM on
//      mcp-server).
//
// WS close is NOT a kill trigger. It only removes the socket from
// `rec.listeners`. The xterm.js panel re-opens its WS on remount
// (refresh / navigation) and reattaches to the same PTY.

/** Fan `output` data out to every attached WS that is still OPEN. */
function fanOutput(rec: PersistentShell, payload: unknown): void {
  const text = JSON.stringify(payload);
  for (const ws of rec.listeners) {
    if (ws.readyState === 1 /* OPEN */) {
      try {
        ws.send(text);
      } catch {
        /* socket closed mid-send */
      }
    }
  }
}

/** Wire a single WS to an existing `PersistentShell` — `input`,
 *  `resize`, `ping` from the browser; nothing about lifecycle (the
 *  record owns the PTY, not the WS). Returns whether the WS was
 *  attached to a pre-existing record (true) or a fresh spawn (false). */
function wireSocketToRecord(socket: WebSocket, rec: PersistentShell, resumed: boolean): void {
  safeSend(socket, {
    type: "started",
    shell: rec.shell,
    cwd: rec.cwd,
    pid: rec.pid,
    resumed,
  });

  socket.on("message", (raw: Buffer | ArrayBuffer | Buffer[]) => {
    if (rec.exited) return;
    let frame: any;
    try {
      frame = JSON.parse(String(raw));
    } catch {
      // Malformed — ignore. The shell shouldn't crash because a
      // keystroke leaked through.
      return;
    }
    switch (frame?.type) {
      case "input": {
        const data = typeof frame.data === "string" ? base64Decode(frame.data) : "";
        if (data) {
          try {
            rec.pty.write(data);
          } catch {
            /* PTY already gone */
          }
        }
        return;
      }
      case "resize": {
        const c = Number(frame.cols);
        const r = Number(frame.rows);
        if (
          Number.isFinite(c) &&
          Number.isFinite(r) &&
          c >= 2 &&
          c <= 500 &&
          r >= 2 &&
          r <= 200
        ) {
          try {
            rec.pty.resize(c, r);
          } catch {
            /* PTY already gone */
          }
        }
        return;
      }
      case "ping": {
        safeSend(socket, { type: "pong", ts: frame.ts });
        return;
      }
      default:
        // Unknown — ignore so a future version's message can be
        // rolled out without breaking older clients.
        return;
    }
  });

  // WS teardown: just drop this socket from the listeners set. The
  // PTY stays alive. This is the entire point of the persistent-shell
  // change — a refresh / navigation / tab close does NOT kill the
  // user's `npm run dev`.
  const detach = () => {
    rec.listeners.delete(socket);
    try {
      socket.removeAllListeners();
    } catch {
      /* */
    }
  };
  socket.on("close", detach);
  socket.on("error", detach);
}

export async function attachShellToSocket(
  socket: WebSocket,
  opts: ShellOptions,
): Promise<ShellInfo> {
  if (!existsSync(opts.cwd) || !statSync(opts.cwd).isDirectory()) {
    throw new Error(`cwd does not exist or is not a directory: ${opts.cwd}`);
  }

  const key = persistentShellKey(opts.workspaceId, opts.cwd, opts.terminalId);
  const existing = persistentShells.get(key);

  // ── Reattach path ───────────────────────────────────────────────
  // A live PTY exists for this (workspace, cwd). Add the new WS as
  // a listener and ship the existing scrollback-free `started` frame
  // with `resumed: true` so the panel can suppress the "fresh prompt"
  // jitter if it wants to. xterm.js paints whatever the PTY emits
  // next; the user's running command continues uninterrupted.
  if (existing && !existing.exited && !existing.stopRequested) {
    existing.listeners.add(socket);
    wireSocketToRecord(socket, existing, /* resumed */ true);
    return {
      shell: existing.shell,
      args: existing.args,
      pid: existing.pid,
      resumed: true,
    };
  }

  // ── Fresh-spawn path ────────────────────────────────────────────
  // Either no record, or the previous one is in the brief "exited but
  // not yet GC'd" window. In both cases we want a brand new PTY. If
  // there is a stale record, drop it now so the new key takes its
  // place cleanly.
  if (existing) persistentShells.delete(key);

  const { shell: shellPath, args } = resolveShellById(opts.shellId);
  const cols = Math.max(2, Math.min(500, opts.cols ?? 80));
  const rows = Math.max(2, Math.min(200, opts.rows ?? 24));

  const pty = await loadPty();
  // Forward only selected env — TERM=xterm-256color is what every
  // terminal emulator expects for ANSI color. PATH inheritance is
  // important so `npm`, `git`, etc. resolve. We don't pass the
  // process env wholesale because mcp-server's own vars (MCP_PORT,
  // AGENT_BRIDGE_TOKEN, …) would leak into user commands and
  // pollute their output.
  const env: Record<string, string> = {
    ...pickEnvSubset(process.env as Record<string, string>),
    ...(opts.env ?? {}),
    TERM: "xterm-256color",
    COLORTERM: "truecolor",
  };
  // On Windows ConPTY ignores TERM, but the child may still consult
  // it (e.g. `git`); set it anyway. FORCE_COLOR keeps npm's
  // progress bar visible inside the panel.
  if (os.platform() === "win32") {
    env.FORCE_COLOR = "1";
  }

  const handle = pty.spawn(shellPath, args, {
    cwd: opts.cwd,
    env,
    cols,
    rows,
    // useConpty=true on Windows forces ConPTY (the modern pseudo-
    // console API); on other platforms it's a no-op.
    useConpty: os.platform() === "win32",
  }) as unknown as Pty;

  const rec: PersistentShell = {
    id: key,
    workspaceId: opts.workspaceId,
    cwd: opts.cwd,
    shell: path.basename(shellPath),
    shellPath,
    args,
    pty: handle,
    pid: handle.pid,
    startedAt: Date.now(),
    lastOutputAt: Date.now(),
    listeners: new Set(),
    exited: false,
    exitCode: null,
    exitSignal: null,
    stopRequested: false,
  };
  persistentShells.set(key, rec);

  // PTY stdout → every attached listener (one today, possibly more
  // after a refresh). We send the JSON once and reuse the same string
  // for each listener — cheaper than serialising per recipient.
  handle.onData((data: string) => {
    rec.lastOutputAt = Date.now();
    fanOutput(rec, { type: "output", data: base64Encode(data) });
  });

  // PTY exit (real — Ctrl+C, `exit`, segfault, anything that ends
  // the shell process). Mark the record, fan out an `exit` frame to
  // every listener, close them, and schedule a 60s GC so a
  // mid-reconnect WS still sees the exit (rather than getting a
  // fresh shell by surprise).
  handle.onExit((e: { exitCode: number; signal?: number }) => {
    rec.exited = true;
    rec.exitCode = e.exitCode;
    rec.exitSignal = typeof e.signal === "number" ? e.signal : null;
    const exitFrame = {
      type: "exit",
      code: e.exitCode,
      signal: typeof e.signal === "number" ? `signal:${e.signal}` : undefined,
      reason: "pty_exit",
    };
    const sockets = [...rec.listeners];
    for (const ws of sockets) {
      safeSend(ws, exitFrame);
      try {
        ws.close(1000, "pty_exit");
      } catch {
        /* already closed */
      }
    }
    rec.listeners.clear();
    setTimeout(() => {
      // Only delete if the record is still us and nobody reattached
      // (which would have flipped `exited` indirectly via the next
      // attach returning a fresh spawn — see attachShellToSocket's
      // reattach path's `!existing.exited` check).
      if (persistentShells.get(key) === rec) {
        persistentShells.delete(key);
      }
    }, PERSISTENT_SHELL_GC_MS);
  });

  rec.listeners.add(socket);
  wireSocketToRecord(socket, rec, /* resumed */ false);

  return {
    shell: rec.shell,
    args: rec.args,
    pid: rec.pid,
    resumed: false,
  };
}

/** Explicit kill — used by the `/dev-terminal/shell/stop` HTTP
 *  route. No UI calls this today (the user types Ctrl+C inside the
 *  terminal), but the route exists for parity with `/dev-server/stop`
 *  and future scripting. */
export async function stopPersistentShell(opts: {
  workspaceId: string;
  cwd: string;
  terminalId: string;
}): Promise<{ ok: true; pid: number | null }> {
  const id = persistentShellKey(opts.workspaceId, opts.cwd, opts.terminalId);
  const rec = persistentShells.get(id);
  if (!rec) return { ok: true, pid: null };

  rec.stopRequested = true;
  const pid = rec.pid;

  // Notify any attached listeners so they flip to "exited" instead
  // of sitting in "reconnecting…" limbo.
  for (const ws of [...rec.listeners]) {
    safeSend(ws, {
      type: "exit",
      code: null,
      signal: "stopped_by_user",
      reason: "stopped_by_user",
    });
    try {
      ws.close(1000, "stopped_by_user");
    } catch {
      /* already closed */
    }
  }
  rec.listeners.clear();

  // Tear down the PTY. node-pty's default kill sends SIGHUP on
  // POSIX and closes the ConPTY handle on Windows — children that
  // don't trap SIGHUP / ignore CTRL_CLOSE_EVENT get reaped; `npm run
  // dev` doesn't trap either, so the dev server dies with the PTY.
  try {
    rec.pty.kill();
  } catch {
    /* already gone */
  }

  rec.exited = true;
  persistentShells.delete(id);
  return { ok: true, pid };
}

/** SIGINT/SIGTERM sweep — kill every persistent PTY. Same shape as
 *  `shutdownAllDevServers` in `devServer.ts:507`. */
export function shutdownAllPersistentShells(): void {
  for (const rec of persistentShells.values()) {
    rec.stopRequested = true;
    for (const ws of [...rec.listeners]) {
      safeSend(ws, {
        type: "exit",
        code: null,
        signal: "server_shutdown",
        reason: "server_shutdown",
      });
      try {
        ws.close(1000, "server_shutdown");
      } catch {
        /* already closed */
      }
    }
    rec.listeners.clear();
    try {
      rec.pty.kill();
    } catch {
      /* already gone */
    }
  }
  persistentShells.clear();
}

// Path guard — the route layer hands us a `cwd` query param. We
// resolve it (which normalizes `..` and `\\`) and require the result
// to be an existing directory. Returning the resolved absolute path
// lets the spawn go off without surprise CWD surprises.
//
// Note: unlike the dev-server file CRUD we do NOT restrict the
// path to the user-picked folder. The terminal is a real shell —
// the user explicitly wants to be able to `cd` elsewhere, install
// global tooling, etc. The "trust the user to run their own
// commands" model applies.
export function safeResolveCwd(cwd: string): string {
  const resolved = resolve(cwd);
  if (!existsSync(resolved) || !statSync(resolved).isDirectory()) {
    throw new Error(`cwd is not a directory: ${cwd}`);
  }
  return resolved;
}

// -- helpers ─────────────────────────────────────────────────────────────

function safeSend(socket: WebSocket, payload: unknown): void {
  try {
    if (socket.readyState === 1 /* OPEN */) {
      socket.send(JSON.stringify(payload));
    }
  } catch {
    /* socket closed mid-send */
  }
}

// Subset of process.env that user shells actually consult. The
// rest (FT-CONFHERE, AGENT_BRIDGE_TOKEN, MCP_PORT, …) would
// either be ignored or actively leak secrets into `env` dumps.
const PASSTHROUGH_ENV = new Set([
  "PATH",
  "Path", // Windows variant
  "HOME",
  "USERPROFILE",
  "HOMEDRIVE",
  "HOMEPATH",
  "LANG",
  "LC_ALL",
  "LC_CTYPE",
  "PWD",
  "SHELL",
  "TMP",
  "TMPDIR",
  "TEMP",
  "USER",
  "LOGNAME",
  "SSH_AUTH_SOCK",
  "DISPLAY",
  "XAUTHORITY",
  "TERM_PROGRAM",
  "GIT_EDITOR",
  "VISUAL",
  "EDITOR",
  "NO_COLOR", // honour user preference
]);
function pickEnvSubset(env: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(env)) {
    if (PASSTHROUGH_ENV.has(k)) out[k] = v;
  }
  return out;
}

// Tiny inline base64 — node-pty outputs strings (not Buffers),
// and keystrokes are usually ASCII, so the JS btoa/atob round-trip
// is fine. Use Buffer under Node because `btoa` only exists in
// the browser and we run server-side here.
function base64Encode(s: string): string {
  return Buffer.from(s, "utf8").toString("base64");
}
function base64Decode(s: string): string {
  try {
    return Buffer.from(s, "base64").toString("utf8");
  } catch {
    return "";
  }
}